# Generated by Django 3.1.13 on 2021-09-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity', models.CharField(choices=[('0', 'Física'), ('1', 'Jurídica')], default='1', max_length=1)),
                ('identity_number', models.CharField(blank=True, default='', max_length=14)),
                ('name', models.CharField(max_length=40, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, default='', max_length=30)),
                ('phone_number', models.CharField(blank=True, default='', max_length=14)),
                ('phone_number2', models.CharField(blank=True, default='', max_length=14)),
                ('cep', models.CharField(blank=True, default='', max_length=8)),
                ('public_place', models.CharField(blank=True, default='', max_length=40)),
                ('address_number', models.CharField(blank=True, default='', max_length=5)),
                ('address_complement', models.CharField(blank=True, default='', max_length=40)),
                ('district', models.CharField(blank=True, default='', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
