# Generated by Django 3.1.13 on 2021-11-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20211023_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nome completo')),
                ('cargo', models.CharField(max_length=20, verbose_name='Nome completo')),
                ('email', models.EmailField(blank=True, default='', max_length=30)),
                ('phone_number', models.CharField(blank=True, default='', max_length=14)),
                ('phone_number2', models.CharField(blank=True, default='', max_length=14)),
                ('active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
