# Generated by Django 3.1.13 on 2021-11-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cargo',
            field=models.CharField(max_length=20, verbose_name='Cargo'),
        ),
    ]
