# Generated by Django 3.1.13 on 2021-11-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20211120_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cargo',
            new_name='position',
        ),
    ]
