# Generated by Django 3.1.13 on 2022-01-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_budgetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrequest',
            name='observation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
