# Generated by Django 3.1.13 on 2022-01-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20220122_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrequest',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
