ERROR = {
    "INVENTORY": {
        "PRODUCT_TYPE": {"PROTECTED": "USICAN.ERROR.INVETORY.PRODUCT_TYPE.PROTECTED"}
    },
    "SALES": {"CUSTOMER": {"PROTECTED": "USICAN.ERROR.SALES.CUSTOMER.PROTECTED"}},
}
