# Generated by Django 3.1.13 on 2021-10-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
