# Generated by Django 3.1.13 on 2021-11-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_producttype_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
